from enum import Enum

class CommunicationProtocolIDs(Enum):
    # Device information
    GET_SET_DEVICE_SN = 0
    GET_SET_DEVICE_NAME = 1
    GET_DEVICE_VERSION = 2
    GET_DEVICE_WITH_L = 3
    GET_DEVICE_TIME = 4
    GET_DEVICE_ID = 5

    # Pose
    GET_POSE = 10
    RESET_POSE = 11
    GET_POSE_L = 13

    # Alarms
    GET_ALARMS_STATE = 20
    CLEAR_ALL_ALARMS_STATE = 21

    # Homing
    SET_GET_HOME_PARAMS = 30
    SET_HOME_CMD = 31
    SET_GET_AUTO_LEVELING = 32

    # Handhold Teaching
    SET_GET_HHTTRIG_MODE = 40
    SET_GET_HHTTRIG_OUTPUT_ENABLED = 41
    GET_HHTTRIG_OUTPUT = 42

    # Arm Orientation
    SET_GET_ARM_ORIENTATION = 50

    # End Effector
    SET_GET_END_EFFECTOR_PARAMS = 60
    SET_GET_END_EFFECTOR_LASER = 61
    SET_GET_END_EFFECTOR_SUCTION_CUP = 62
    SET_GET_END_EFFECTOR_GRIPPER = 63

    # JOG Commands
    SET_GET_JOG_JOINT_PARAMS = 70
    SET_GET_JOG_COORDINATE_PARAMS = 71
    SET_GET_JOG_COMMON_PARAMS = 72
    SET_JOG_CMD = 73
    SET_GET_JOG_L_PARAMS = 74

    # PTP Commands
    SET_GET_PTP_JOINT_PARAMS = 80
    SET_GET_PTP_COORDINATE_PARAMS = 81
    SET_GET_PTP_JUMP_PARAMS = 82
    SET_GET_PTP_COMMON_PARAMS = 83
    SET_PTP_CMD = 84
    SET_GET_PTP_L_PARAMS = 85
    SET_PTP_WITH_L_CMD = 86

    # CP Commands
    SET_GET_CP_PARAMS = 90
    SET_CP_CMD = 91
    SET_CP_LE_CMD = 92

    # ARC Commands
    SET_GET_ARC_PARAMS = 100
    SET_ARC_CMD = 101

    # WAIT Command
    SET_WAIT_CMD = 110

    # TRIG Command
    SET_TRIG_CMD = 120

    # EIO Commands
    SET_GET_EIO_MULTIPLEXING = 130
    SET_GET_EIO = 131
    SET_GET_IO_PWM = 132
    GET_IO_DI = 133
    GET_IO_ADC = 134
    SET_GET_COLOR_SENSOR = 137
    SET_GET_IR_SWITCH = 138

    # Calibration
    SET_GET_ANGLE_SENSOR_STATIC_ERROR = 140

    # WiFi Commands
    SET_GET_WIFI_CONFIG_MODE = 150
    SET_GET_WIFI_SSID = 151
    SET_GET_WIFI_PASSWORD = 152
    SET_GET_WIFI_IP_ADDRESS = 153
    SET_GET_WIFI_NETMASK = 154
    SET_GET_WIFI_GATEWAY = 155
    SET_GET_WIFI_DNS = 156
    GET_WIFI_CONNECT_STATUS = 157

    # Step Detection
    SET_LOST_STEP_PARAMS = 158
    SET_LOST_STEP_CMD = 159

    # Queued Execution Control
    SET_QUEUED_CMD_START_EXEC = 240
    SET_QUEUED_CMD_STOP_EXEC = 241
    SET_QUEUED_CMD_FORCE_STOP_EXEC = 242
    SET_QUEUED_CMD_START_DOWNLOAD = 243
    SET_QUEUED_CMD_STOP_DOWNLOAD = 244
    SET_QUEUED_CMD_CLEAR = 245
    GET_QUEUED_CMD_CURRENT_INDEX = 246
